services:
  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_backend
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    command: sh -c "composer install && cp -n .env.example .env && php artisan key:generate && until php artisan migrate --force; do sleep 2; done && php artisan serve --host=0.0.0.0 --port=8000"
    depends_on:
      - db

  frontend:
    image: node:22-alpine
    container_name: vue_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  db:
    image: mariadb:10.11
    container_name: mariadb_db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: app
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
