services:
  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_backend
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - db

  frontend:
    image: node:26
    container_name: vue_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  nginx:
    image: nginx:1.31
    container_name: nginx_server
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  db:
    image: mariadb:12.2.2
    container_name: mariadb_db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: app
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
